import type { LessonContent } from './types'

// Markdown 形式のレッスン(src/content/<id>.md。書き方は docs/lesson-format.md)。md('id') と書く。
const mdSources = import.meta.glob('../content/*.md', { query: '?raw', import: 'default' }) as Record<string, () => Promise<string>>
const md = (id: string) => () =>
  import('./markdown').then((m) => m.loadMarkdown(id, mdSources[`../content/${id}.md`]().then((source) => ({ default: source }))))

// 登録したレッスンだけが公開扱い。本文は動的importで遅延読み込みする。
const loaders: Record<string, () => Promise<{ default: LessonContent }>> = {
  'i-1': () => import('./IntroMap'),
  'i-2': () => import('./History'),
  '0-1': () => import('./VectorMatrix'),
  '0-2': () => import('./Probability'),
  '0-3': () => import('./Gradient'),
  '1-1': () => import('./LossFunction'),
  '1-2': () => import('./GradientDescent'),
  '1-3': () => import('./Overfitting'),
  '2-1': () => import('./Neuron'),
  '2-2': () => import('./Activation'),
  '2-3': () => import('./Backprop'),
  '3-1': () => import('./Tokenization'),
  '3-2': () => import('./Embedding'),
  '3-3': () => import('./LanguageModel'),
  '5-1': () => import('./NextToken'),
  '5-2': () => import('./TrainingData'),
  '5-3': () => import('./ScalingLaw'),
  '6-1': () => import('./Sampling'),
  '6-2': () => import('./KvCache'),
  '6-3': () => import('./ContextWindow'),
  '7-1': () => import('./Sft'),
  '7-2': () => import('./Rlhf'),
  '7-3': () => import('./Alignment'),
  '8-1': () => import('./Rag'),
  '8-2': () => import('./Agent'),
  '8-3': () => import('./Hallucination'),
  '9-1': () => import('./ApiBasics'),
  '9-2': () => import('./ApiResponses'),
  '9-3': () => import('./PromptDesign'),
  '9-4': () => import('./StructuredOutput'),
  '10-1': () => import('./ToolDefinition'),
  '10-2': () => import('./ToolLoop'),
  '10-3': () => import('./ToolDesign'),
  '10-4': () => import('./Mcp'),
  '11-1': () => import('./WorkflowsVsAgents'),
  '11-2': () => import('./AgentLoop'),
  '11-3': () => import('./ContextMemory'),
  '11-4': () => import('./RagImplementation'),
  '11-5': () => import('./MultiAgent'),
  '12-1': () => import('./EvalAgents'),
  '12-2': () => import('./AgentSecurity'),
  '12-3': () => import('./Production'),
  '13-1': () => import('./CapstoneDesign'),
  '13-2': () => import('./CapstoneCode'),
  '13-3': () => import('./CapstoneEval'),
  '14-1': () => import('./AiDevLevels'),
  '14-2': () => import('./AiDevEvidence'),
  '14-3': () => import('./ChooseLevel'),
  '15-1': () => import('./AssistBasics'),
  '15-2': () => import('./ReviewGenerated'),
  '15-3': () => import('./LearnWithAi'),
  '16-1': () => import('./AgentWorkflow'),
  '16-2': () => import('./ProjectContext'),
  '16-3': () => import('./AgentPermissions'),
  '17-1': () => import('./DelegateIssue'),
  '17-2': () => import('./CiGuardrails'),
  '17-3': () => import('./MeasureAdoption'),
  '18-1': () => import('./IntentVerification'),
  '18-2': () => import('./ContinuousLoops'),
  '18-3': () => import('./L5Risks'),
  '19-1': () => import('./SelfAssessment'),
  '19-2': () => import('./MigrationPlan'),
  '19-3': () => import('./CaseStudy'),
  '20-1': () => import('./McpServerBuild'),
  '20-2': () => import('./EvalAutomation'),
  '20-3': () => import('./CacheCost'),
  'e-1': () => import('./EvidenceIntro'),
  'e-2': md('e-2'),
  'e-3': md('e-3'),
  'e-4': md('e-4'),
  'e-5': md('e-5'),
  'st-1': md('st-1'),
  '4-1': () => import('./WhyAttention'),
  '4-2': () => import('./SelfAttention'),
  '4-3': () => import('./PositionalEncoding'),
  '4-4': () => import('./TransformerBlock'),
}

export const lessonIds = Object.keys(loaders)
export const isReady = (id: string) => id in loaders
export const loadLessonContent = (id: string) => loaders[id]().then((m) => m.default)
