import type { LessonContent } from './types'

// Markdown 形式のレッスン(src/content/<id>.md。書き方は docs/lesson-format.md)。md('id') と書く。
const mdSources = import.meta.glob('../content/*.md', { query: '?raw', import: 'default' }) as Record<string, () => Promise<string>>
const md = (id: string) => () =>
  import('./markdown').then((m) => m.loadMarkdown(id, mdSources[`../content/${id}.md`]().then((source) => ({ default: source }))))

// 登録したレッスンだけが公開扱い。本文は動的importで遅延読み込みする。
const loaders: Record<string, () => Promise<{ default: LessonContent }>> = {
  'i-1': () => import('./IntroMap'),
  'i-2': () => import('./History'),
  '0-1': () => import('./VectorMatrix'),
  '0-2': () => import('./Probability'),
  '0-3': () => import('./Gradient'),
  '1-1': () => import('./LossFunction'),
  '1-2': () => import('./GradientDescent'),
  '1-3': () => import('./Overfitting'),
  '2-1': () => import('./Neuron'),
  '2-2': () => import('./Activation'),
  '2-3': () => import('./Backprop'),
  '3-1': () => import('./Tokenization'),
  '3-2': () => import('./Embedding'),
  '3-3': () => import('./LanguageModel'),
  '5-1': () => import('./NextToken'),
  '5-2': () => import('./TrainingData'),
  '5-3': () => import('./ScalingLaw'),
  '6-1': () => import('./Sampling'),
  '6-2': () => import('./KvCache'),
  '6-3': () => import('./ContextWindow'),
  '7-1': () => import('./Sft'),
  '7-2': () => import('./Rlhf'),
  '7-3': () => import('./Alignment'),
  '8-1': () => import('./Rag'),
  '8-2': () => import('./Agent'),
  '8-3': () => import('./Hallucination'),
  '9-1': () => import('./ApiBasics'),
  '9-2': () => import('./ApiResponses'),
  '9-3': () => import('./PromptDesign'),
  '9-4': () => import('./StructuredOutput'),
  '10-1': () => import('./ToolDefinition'),
  '10-2': () => import('./ToolLoop'),
  '10-3': () => import('./ToolDesign'),
  '10-4': () => import('./Mcp'),
  '11-1': () => import('./WorkflowsVsAgents'),
  '11-2': () => import('./AgentLoop'),
  '11-3': () => import('./ContextMemory'),
  '11-4': () => import('./RagImplementation'),
  '11-5': () => import('./MultiAgent'),
  '12-1': () => import('./EvalAgents'),
  '12-2': () => import('./AgentSecurity'),
  '12-3': () => import('./Production'),
  '13-1': () => import('./CapstoneDesign'),
  '13-2': () => import('./CapstoneCode'),
  '13-3': () => import('./CapstoneEval'),
  '14-1': () => import('./AiDevLevels'),
  '14-2': () => import('./AiDevEvidence'),
  '14-3': () => import('./ChooseLevel'),
  '15-1': () => import('./AssistBasics'),
  '15-2': () => import('./ReviewGenerated'),
  '15-3': () => import('./LearnWithAi'),
  '16-1': () => import('./AgentWorkflow'),
  '16-2': () => import('./ProjectContext'),
  '16-3': () => import('./AgentPermissions'),
  '17-1': () => import('./DelegateIssue'),
  '17-2': () => import('./CiGuardrails'),
  '17-3': () => import('./MeasureAdoption'),
  '18-1': () => import('./IntentVerification'),
  '18-2': () => import('./ContinuousLoops'),
  '18-3': () => import('./L5Risks'),
  '19-1': () => import('./SelfAssessment'),
  '19-2': () => import('./MigrationPlan'),
  '19-3': () => import('./CaseStudy'),
  '20-1': () => import('./McpServerBuild'),
  '20-2': () => import('./EvalAutomation'),
  '20-3': () => import('./CacheCost'),
  'e-1': () => import('./EvidenceIntro'),
  'e-2': md('e-2'),
  'e-3': md('e-3'),
  'e-4': md('e-4'),
  'e-5': md('e-5'),
  'st-1': md('st-1'),
  'st-2': md('st-2'),
  'st-3': md('st-3'),
  'st-4': md('st-4'),
  'st-5': md('st-5'),
  'st-6': md('st-6'),
  'sg-1': md('sg-1'),
  'sg-2': md('sg-2'),
  'sg-3': md('sg-3'),
  'sg-4': md('sg-4'),
  'sg-5': md('sg-5'),
  'sg-6': md('sg-6'),
  'ps-1': md('ps-1'),
  'ps-2': md('ps-2'),
  'ps-3': md('ps-3'),
  'ps-4': md('ps-4'),
  'ps-5': md('ps-5'),
  'ps-6': md('ps-6'),
  'ux-1': md('ux-1'),
  'ux-2': md('ux-2'),
  'ux-3': md('ux-3'),
  'ux-4': md('ux-4'),
  'ux-5': md('ux-5'),
  'ux-6': md('ux-6'),
  'pm-1': md('pm-1'),
  'pm-2': md('pm-2'),
  'pm-3': md('pm-3'),
  'pm-4': md('pm-4'),
  'pm-5': md('pm-5'),
  'pm-6': md('pm-6'),
  'pm-7': md('pm-7'),
  'ln-1': md('ln-1'),
  'ln-2': md('ln-2'),
  'ln-3': md('ln-3'),
  'ln-4': md('ln-4'),
  'ln-5': md('ln-5'),
  'ln-6': md('ln-6'),
  'ma-1': md('ma-1'),
  'ma-2': md('ma-2'),
  'ma-3': md('ma-3'),
  'ma-4': md('ma-4'),
  'ma-5': md('ma-5'),
  'ma-6': md('ma-6'),
  'bh-1': md('bh-1'),
  'bh-2': md('bh-2'),
  'bh-3': md('bh-3'),
  'bh-4': md('bh-4'),
  'bh-5': md('bh-5'),
  'bh-6': md('bh-6'),
  'mg-1': md('mg-1'),
  'mg-2': md('mg-2'),
  'mg-3': md('mg-3'),
  'mg-4': md('mg-4'),
  'mg-5': md('mg-5'),
  'mg-6': md('mg-6'),
  '4-1': () => import('./WhyAttention'),
  '4-2': () => import('./SelfAttention'),
  '4-3': () => import('./PositionalEncoding'),
  '4-4': () => import('./TransformerBlock'),
}

export const lessonIds = Object.keys(loaders)
export const isReady = (id: string) => id in loaders
export const loadLessonContent = (id: string) => loaders[id]().then((m) => m.default)
